name: GodComplex
main: Main.Main
version: 2.0
authors: [Lacom, Jozeth]
website: http://godcomplex.ultrablock.hu
commands:
   10011001:
   terulet:
   viphelp:
   chest:
   craft:
   merch:
   table:
   fej:
   biztosit:
   replace_near:
   nether:
   portal:
   end:
   r:
   szint:
   clean:
   clear:
   rang:
   gm:
   szef:
   haza:
   tp:
   ide:
   vissza:
   spawn:
   ktp:
   reggel:
   este:
   setspawn:
   kivesz:
   mob:
   memory:
   l:
   ip:
   ban:
   unban:
   kick:
   help:
   modhelp:
   pvp:
   cc:
   szeret:
   h:
   kuka:
   fly:
   pia:
   ima:
   inv:
   ruha:
   i:
   kalap:
   bl:
   utoljara:
   m:
   jg:
   me:
   welcome:
   tpbe:
   tpki:
   book:
   duhongo:
   man:
   penz:
   pont:
   atm:
   vesz:
   utal:
   debug:
   v:
   hv:
   more:
   karma:
   ido:
   dob:
   say:
   pri:
   lotto:
   level:
   posta:
   button:
   fx:
   id:
   login:
   register:
   tour:
   lift:
   alma:
   luck:
   list:
   msg:
   warp:
   altop: